### ISSUE TITLE
2hop_neighbor_myindex.pickle

### ISSUE THREAD

**Issue by kg-embedding** [Juanhui28/Are_MPNNs_helpful#2]
Can you provide the 2hop_neighbor_myindex.pickle of FB15k and WN18? Or you can tell how to produce it

**Comment by Juanhui28** [comment]
Thanks for letting me know. Actually we don't need this file '2hop_neighbor_myindex.pickle' . You may need to load it when the flag '--use_feat_input' is true. Please set this flag to be false
